### ISSUE TITLE
Wave 4

### ISSUE THREAD

**Issue by DANLCARTON** [DANLCARTON/Mario-Kart-Randomizer#7]
# Partie personnages
## Nouveau  personnage : Birdo !!
- [x] Nouvelles images (gestion des différents skins !!!) : attention voir #6 [possible source](https://www.mariowiki.com/Mario_Kart_8_Deluxe#Characters)
- [x] Trouver ses statistiques : [possible source](https://www.mariowiki.com/Mario_Kart_8_Deluxe#Drivers'_statistics)

# Partie Circuits
## Nouvelles coupes : Coupe Fruit et Coupe Boomerang !!!
- [x] Trouver des nouvelles images : encore une fois attention à #6 [possible source](https://www.mariowiki.com/Mario_Kart_8_Deluxe#Booster_Course_Pass)
- [x] Ajouter les coupes dans le code, avec le nom des circuits ok

# Partie objets
- [x] changer la description de la partie

# Autres
## Changements esthétiques
- [x] couleur du fond du thème clair : orange et bleu pour correspondre aux coupes comme j'ai fait jusqu'à maintenant, ou on trouve une couleur définitive (j'aimerais bien) ???
- [x] changer la couleur de l'interface google chrome android
- [x] changer la couleur des sélections en fonction des couleur du fond

## Autres
- [x] Rédiger le README
- [x] faire tout ce qui est dans #6 en gros
- [x] faire aussi #5
